Exception in thread Thread-98:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-92:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-73:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-96:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-82:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-86:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-74:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-89:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-87:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./upgrade.py", line 26, in run
    req.get_request(proid);
  File "/home/adc/public/virtualJudge/mybin/getReq.py", line 82, in get_request
    self.get_title();
  File "/home/adc/public/virtualJudge/mybin/getHdu.py", line 89, in get_title
    self.title = p.group(1);
AttributeError: 'NoneType' object has no attribute 'group'

